
var __cov_L0XHDKSh2tE$DQM0waInzw = (Function('return this'))();
if (!__cov_L0XHDKSh2tE$DQM0waInzw.__coverage__) { __cov_L0XHDKSh2tE$DQM0waInzw.__coverage__ = {}; }
__cov_L0XHDKSh2tE$DQM0waInzw = __cov_L0XHDKSh2tE$DQM0waInzw.__coverage__;
if (!(__cov_L0XHDKSh2tE$DQM0waInzw['/Users/Work/www/Projects/nlp_compromise/test/unit_test/article_test.js'])) {
   __cov_L0XHDKSh2tE$DQM0waInzw['/Users/Work/www/Projects/nlp_compromise/test/unit_test/article_test.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/unit_test/article_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0},"b":{},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"(anonymous_1)","line":5,"loc":{"start":{"line":5,"column":20},"end":{"line":5,"column":32}}},"2":{"name":"(anonymous_2)","line":16,"loc":{"start":{"line":16,"column":12},"end":{"line":16,"column":25}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":31}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":45}},"4":{"start":{"line":5,"column":0},"end":{"line":21,"column":3}},"5":{"start":{"line":6,"column":2},"end":{"line":19,"column":5}},"6":{"start":{"line":17,"column":4},"end":{"line":17,"column":39}},"7":{"start":{"line":18,"column":4},"end":{"line":18,"column":33}},"8":{"start":{"line":20,"column":2},"end":{"line":20,"column":10}}},"branchMap":{}};
}
__cov_L0XHDKSh2tE$DQM0waInzw = __cov_L0XHDKSh2tE$DQM0waInzw['/Users/Work/www/Projects/nlp_compromise/test/unit_test/article_test.js'];
__cov_L0XHDKSh2tE$DQM0waInzw.s['1']++;var test=require('tape');__cov_L0XHDKSh2tE$DQM0waInzw.s['2']++;var nlp=require('./lib/nlp');__cov_L0XHDKSh2tE$DQM0waInzw.s['3']++;var str_test=require('./lib/fns').str_test;__cov_L0XHDKSh2tE$DQM0waInzw.s['4']++;test('.article():',function(t){__cov_L0XHDKSh2tE$DQM0waInzw.f['1']++;__cov_L0XHDKSh2tE$DQM0waInzw.s['5']++;[['duck','a'],['eavesdropper','an'],['alligator','an'],['hour','an'],['NDA','an'],['F.B.I','an'],['N.D.A.','an'],['eulogy','a'],['ukalele','a']].forEach(function(a){__cov_L0XHDKSh2tE$DQM0waInzw.f['2']++;__cov_L0XHDKSh2tE$DQM0waInzw.s['6']++;var str=nlp.noun(a[0]).article();__cov_L0XHDKSh2tE$DQM0waInzw.s['7']++;str_test(str,a[0],a[1],t);});__cov_L0XHDKSh2tE$DQM0waInzw.s['8']++;t.end();});
