
var __cov_AzTRdHnsrw9bmJEjTX6vgw = (Function('return this'))();
if (!__cov_AzTRdHnsrw9bmJEjTX6vgw.__coverage__) { __cov_AzTRdHnsrw9bmJEjTX6vgw.__coverage__ = {}; }
__cov_AzTRdHnsrw9bmJEjTX6vgw = __cov_AzTRdHnsrw9bmJEjTX6vgw.__coverage__;
if (!(__cov_AzTRdHnsrw9bmJEjTX6vgw['/Users/Work/www/Projects/nlp_compromise/test/unit_test/conditions_test.js'])) {
   __cov_AzTRdHnsrw9bmJEjTX6vgw['/Users/Work/www/Projects/nlp_compromise/test/unit_test/conditions_test.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/unit_test/conditions_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0},"b":{},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"(anonymous_1)","line":6,"loc":{"start":{"line":6,"column":20},"end":{"line":6,"column":32}}},"2":{"name":"(anonymous_2)","line":10,"loc":{"start":{"line":10,"column":12},"end":{"line":10,"column":25}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":31}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":45}},"4":{"start":{"line":6,"column":0},"end":{"line":15,"column":3}},"5":{"start":{"line":7,"column":2},"end":{"line":13,"column":5}},"6":{"start":{"line":11,"column":4},"end":{"line":11,"column":59}},"7":{"start":{"line":12,"column":4},"end":{"line":12,"column":33}},"8":{"start":{"line":14,"column":2},"end":{"line":14,"column":10}}},"branchMap":{}};
}
__cov_AzTRdHnsrw9bmJEjTX6vgw = __cov_AzTRdHnsrw9bmJEjTX6vgw['/Users/Work/www/Projects/nlp_compromise/test/unit_test/conditions_test.js'];
__cov_AzTRdHnsrw9bmJEjTX6vgw.s['1']++;var test=require('tape');__cov_AzTRdHnsrw9bmJEjTX6vgw.s['2']++;var nlp=require('./lib/nlp');__cov_AzTRdHnsrw9bmJEjTX6vgw.s['3']++;var str_test=require('./lib/fns').str_test;__cov_AzTRdHnsrw9bmJEjTX6vgw.s['4']++;test('conditions:',function(t){__cov_AzTRdHnsrw9bmJEjTX6vgw.f['1']++;__cov_AzTRdHnsrw9bmJEjTX6vgw.s['5']++;[['if it is raining, the driveway is wet','the driveway is wet'],['if it is raining, the driveway is wet, unless it is snowing','the driveway is wet']].forEach(function(a){__cov_AzTRdHnsrw9bmJEjTX6vgw.f['2']++;__cov_AzTRdHnsrw9bmJEjTX6vgw.s['6']++;var str=nlp.sentence(a[0]).strip_conditions().text();__cov_AzTRdHnsrw9bmJEjTX6vgw.s['7']++;str_test(str,a[0],a[1],t);});__cov_AzTRdHnsrw9bmJEjTX6vgw.s['8']++;t.end();});
