
var __cov_0CjdK5bjNLd4PPkVzd7dCg = (Function('return this'))();
if (!__cov_0CjdK5bjNLd4PPkVzd7dCg.__coverage__) { __cov_0CjdK5bjNLd4PPkVzd7dCg.__coverage__ = {}; }
__cov_0CjdK5bjNLd4PPkVzd7dCg = __cov_0CjdK5bjNLd4PPkVzd7dCg.__coverage__;
if (!(__cov_0CjdK5bjNLd4PPkVzd7dCg['/Users/Work/www/Projects/nlp_compromise/test/unit_test/lumper_test.js'])) {
   __cov_0CjdK5bjNLd4PPkVzd7dCg['/Users/Work/www/Projects/nlp_compromise/test/unit_test/lumper_test.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/unit_test/lumper_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0},"b":{},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"(anonymous_1)","line":5,"loc":{"start":{"line":5,"column":21},"end":{"line":5,"column":33}}},"2":{"name":"(anonymous_2)","line":21,"loc":{"start":{"line":21,"column":12},"end":{"line":21,"column":25}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":31}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":45}},"4":{"start":{"line":5,"column":0},"end":{"line":26,"column":3}},"5":{"start":{"line":6,"column":2},"end":{"line":24,"column":5}},"6":{"start":{"line":22,"column":4},"end":{"line":22,"column":41}},"7":{"start":{"line":23,"column":4},"end":{"line":23,"column":29}},"8":{"start":{"line":25,"column":2},"end":{"line":25,"column":10}}},"branchMap":{}};
}
__cov_0CjdK5bjNLd4PPkVzd7dCg = __cov_0CjdK5bjNLd4PPkVzd7dCg['/Users/Work/www/Projects/nlp_compromise/test/unit_test/lumper_test.js'];
__cov_0CjdK5bjNLd4PPkVzd7dCg.s['1']++;var test=require('tape');__cov_0CjdK5bjNLd4PPkVzd7dCg.s['2']++;var nlp=require('./lib/nlp');__cov_0CjdK5bjNLd4PPkVzd7dCg.s['3']++;var pos_test=require('./lib/fns').pos_test;__cov_0CjdK5bjNLd4PPkVzd7dCg.s['4']++;test('lumper test:',function(t){__cov_0CjdK5bjNLd4PPkVzd7dCg.f['1']++;__cov_0CjdK5bjNLd4PPkVzd7dCg.s['5']++;[['John Baseball',['Person']],['John sr.',['Person']],['Dr. John',['Person']],['she said "dutch oven"',['Person','PastTense','Quotation']],['she said "huge dutch oven"',['Person','PastTense','Quotation']],['the Captain of Jamaica',['Determiner','Noun']],['joe will have walked',['Person','Verb']],['joe had walked',['Person','Verb']]].forEach(function(a){__cov_0CjdK5bjNLd4PPkVzd7dCg.f['2']++;__cov_0CjdK5bjNLd4PPkVzd7dCg.s['6']++;var terms=nlp.sentence(a[0]).terms;__cov_0CjdK5bjNLd4PPkVzd7dCg.s['7']++;pos_test(terms,a[1],t);});__cov_0CjdK5bjNLd4PPkVzd7dCg.s['8']++;t.end();});
