
var __cov_0sT5JkQLWvIZPjCobAoF3Q = (Function('return this'))();
if (!__cov_0sT5JkQLWvIZPjCobAoF3Q.__coverage__) { __cov_0sT5JkQLWvIZPjCobAoF3Q.__coverage__ = {}; }
__cov_0sT5JkQLWvIZPjCobAoF3Q = __cov_0sT5JkQLWvIZPjCobAoF3Q.__coverage__;
if (!(__cov_0sT5JkQLWvIZPjCobAoF3Q['/Users/Work/www/Projects/nlp_compromise/test/unit_test/normalize_test.js'])) {
   __cov_0sT5JkQLWvIZPjCobAoF3Q['/Users/Work/www/Projects/nlp_compromise/test/unit_test/normalize_test.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/unit_test/normalize_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0},"b":{},"f":{"1":0,"2":0,"3":0,"4":0,"5":0},"fnMap":{"1":{"name":"(anonymous_1)","line":5,"loc":{"start":{"line":5,"column":22},"end":{"line":5,"column":34}}},"2":{"name":"(anonymous_2)","line":7,"loc":{"start":{"line":7,"column":24},"end":{"line":7,"column":36}}},"3":{"name":"(anonymous_3)","line":12,"loc":{"start":{"line":12,"column":14},"end":{"line":12,"column":27}}},"4":{"name":"(anonymous_4)","line":19,"loc":{"start":{"line":19,"column":20},"end":{"line":19,"column":32}}},"5":{"name":"(anonymous_5)","line":24,"loc":{"start":{"line":24,"column":14},"end":{"line":24,"column":27}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":31}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":45}},"4":{"start":{"line":5,"column":0},"end":{"line":30,"column":3}},"5":{"start":{"line":7,"column":2},"end":{"line":17,"column":5}},"6":{"start":{"line":8,"column":4},"end":{"line":15,"column":7}},"7":{"start":{"line":13,"column":6},"end":{"line":13,"column":44}},"8":{"start":{"line":14,"column":6},"end":{"line":14,"column":35}},"9":{"start":{"line":16,"column":4},"end":{"line":16,"column":12}},"10":{"start":{"line":19,"column":2},"end":{"line":29,"column":5}},"11":{"start":{"line":20,"column":4},"end":{"line":27,"column":7}},"12":{"start":{"line":25,"column":6},"end":{"line":25,"column":40}},"13":{"start":{"line":26,"column":6},"end":{"line":26,"column":35}},"14":{"start":{"line":28,"column":4},"end":{"line":28,"column":12}}},"branchMap":{}};
}
__cov_0sT5JkQLWvIZPjCobAoF3Q = __cov_0sT5JkQLWvIZPjCobAoF3Q['/Users/Work/www/Projects/nlp_compromise/test/unit_test/normalize_test.js'];
__cov_0sT5JkQLWvIZPjCobAoF3Q.s['1']++;var test=require('tape');__cov_0sT5JkQLWvIZPjCobAoF3Q.s['2']++;var nlp=require('./lib/nlp');__cov_0sT5JkQLWvIZPjCobAoF3Q.s['3']++;var str_test=require('./lib/fns').str_test;__cov_0sT5JkQLWvIZPjCobAoF3Q.s['4']++;test('==Normalize==',function(T){__cov_0sT5JkQLWvIZPjCobAoF3Q.f['1']++;__cov_0sT5JkQLWvIZPjCobAoF3Q.s['5']++;T.test('sentence():',function(t){__cov_0sT5JkQLWvIZPjCobAoF3Q.f['2']++;__cov_0sT5JkQLWvIZPjCobAoF3Q.s['6']++;[['he is good','he is good'],['Jack and Jill went up the hill.','jack and jill went up the hill.'],['Mr. Clinton did so.','mr clinton did so.']].forEach(function(a){__cov_0sT5JkQLWvIZPjCobAoF3Q.f['3']++;__cov_0sT5JkQLWvIZPjCobAoF3Q.s['7']++;var str=nlp.sentence(a[0]).normal();__cov_0sT5JkQLWvIZPjCobAoF3Q.s['8']++;str_test(str,a[0],a[1],t);});__cov_0sT5JkQLWvIZPjCobAoF3Q.s['9']++;t.end();});__cov_0sT5JkQLWvIZPjCobAoF3Q.s['10']++;T.test('text():',function(t){__cov_0sT5JkQLWvIZPjCobAoF3Q.f['4']++;__cov_0sT5JkQLWvIZPjCobAoF3Q.s['11']++;[['he is good','he is good'],['Jack and Jill   went up the hill. She got  water.','jack and jill went up the hill. she got water.']].forEach(function(a){__cov_0sT5JkQLWvIZPjCobAoF3Q.f['5']++;__cov_0sT5JkQLWvIZPjCobAoF3Q.s['12']++;var str=nlp.text(a[0]).normal();__cov_0sT5JkQLWvIZPjCobAoF3Q.s['13']++;str_test(str,a[0],a[1],t);});__cov_0sT5JkQLWvIZPjCobAoF3Q.s['14']++;t.end();});});
