
var __cov_VtdytR$rwc12fxOhEbDHnw = (Function('return this'))();
if (!__cov_VtdytR$rwc12fxOhEbDHnw.__coverage__) { __cov_VtdytR$rwc12fxOhEbDHnw.__coverage__ = {}; }
__cov_VtdytR$rwc12fxOhEbDHnw = __cov_VtdytR$rwc12fxOhEbDHnw.__coverage__;
if (!(__cov_VtdytR$rwc12fxOhEbDHnw['/Users/Work/www/Projects/nlp_compromise/test/unit_test/passive_voice_test.js'])) {
   __cov_VtdytR$rwc12fxOhEbDHnw['/Users/Work/www/Projects/nlp_compromise/test/unit_test/passive_voice_test.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/unit_test/passive_voice_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0},"b":{},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"(anonymous_1)","line":4,"loc":{"start":{"line":4,"column":23},"end":{"line":4,"column":35}}},"2":{"name":"(anonymous_2)","line":10,"loc":{"start":{"line":10,"column":12},"end":{"line":10,"column":25}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":31}},"3":{"start":{"line":4,"column":0},"end":{"line":16,"column":3}},"4":{"start":{"line":5,"column":2},"end":{"line":14,"column":5}},"5":{"start":{"line":11,"column":4},"end":{"line":11,"column":47}},"6":{"start":{"line":12,"column":4},"end":{"line":12,"column":35}},"7":{"start":{"line":13,"column":4},"end":{"line":13,"column":29}},"8":{"start":{"line":15,"column":2},"end":{"line":15,"column":10}}},"branchMap":{}};
}
__cov_VtdytR$rwc12fxOhEbDHnw = __cov_VtdytR$rwc12fxOhEbDHnw['/Users/Work/www/Projects/nlp_compromise/test/unit_test/passive_voice_test.js'];
__cov_VtdytR$rwc12fxOhEbDHnw.s['1']++;var test=require('tape');__cov_VtdytR$rwc12fxOhEbDHnw.s['2']++;var nlp=require('./lib/nlp');__cov_VtdytR$rwc12fxOhEbDHnw.s['3']++;test('passive-voice:',function(t){__cov_VtdytR$rwc12fxOhEbDHnw.f['1']++;__cov_VtdytR$rwc12fxOhEbDHnw.s['4']++;[['the drink was drank by me',true],['baghdad was flooded by the river',true],['My birthday was approaching by June 5th',false],['Oh say can you see? By the dawn\'s early rise.',false]].forEach(function(a){__cov_VtdytR$rwc12fxOhEbDHnw.f['2']++;__cov_VtdytR$rwc12fxOhEbDHnw.s['5']++;var bool=nlp.sentence(a[0]).is_passive();__cov_VtdytR$rwc12fxOhEbDHnw.s['6']++;var msg=a[0]+' is passive';__cov_VtdytR$rwc12fxOhEbDHnw.s['7']++;t.equal(bool,a[1],msg);});__cov_VtdytR$rwc12fxOhEbDHnw.s['8']++;t.end();});
