
var __cov_KrQDL2pebAJolgCOza8ldg = (Function('return this'))();
if (!__cov_KrQDL2pebAJolgCOza8ldg.__coverage__) { __cov_KrQDL2pebAJolgCOza8ldg.__coverage__ = {}; }
__cov_KrQDL2pebAJolgCOza8ldg = __cov_KrQDL2pebAJolgCOza8ldg.__coverage__;
if (!(__cov_KrQDL2pebAJolgCOza8ldg['/Users/Work/www/Projects/nlp_compromise/test/unit_test/phrasal_test.js'])) {
   __cov_KrQDL2pebAJolgCOza8ldg['/Users/Work/www/Projects/nlp_compromise/test/unit_test/phrasal_test.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/unit_test/phrasal_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0},"b":{},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"(anonymous_1)","line":6,"loc":{"start":{"line":6,"column":23},"end":{"line":6,"column":35}}},"2":{"name":"(anonymous_2)","line":18,"loc":{"start":{"line":18,"column":12},"end":{"line":18,"column":25}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":31}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":49}},"4":{"start":{"line":6,"column":0},"end":{"line":23,"column":3}},"5":{"start":{"line":7,"column":2},"end":{"line":21,"column":5}},"6":{"start":{"line":19,"column":4},"end":{"line":19,"column":41}},"7":{"start":{"line":20,"column":4},"end":{"line":20,"column":31}},"8":{"start":{"line":22,"column":2},"end":{"line":22,"column":10}}},"branchMap":{}};
}
__cov_KrQDL2pebAJolgCOza8ldg = __cov_KrQDL2pebAJolgCOza8ldg['/Users/Work/www/Projects/nlp_compromise/test/unit_test/phrasal_test.js'];
__cov_KrQDL2pebAJolgCOza8ldg.s['1']++;var test=require('tape');__cov_KrQDL2pebAJolgCOza8ldg.s['2']++;var nlp=require('./lib/nlp');__cov_KrQDL2pebAJolgCOza8ldg.s['3']++;var terms_test=require('./lib/fns').terms_test;__cov_KrQDL2pebAJolgCOza8ldg.s['4']++;test('phrasal-verbs:',function(t){__cov_KrQDL2pebAJolgCOza8ldg.f['1']++;__cov_KrQDL2pebAJolgCOza8ldg.s['5']++;[[`he is really good`,['he','is','really','good']],[`he is upset about it`,['he','is','upset','about','it']],[`he will mess about with it`,['he','will mess about','with','it']],[`come forward`,['come forward']],[`come together`,['come together']],[`come apart`,['come apart']],[`frighten back`,['frighten','back']],[`frighten away`,['frighten away']]].forEach(function(a){__cov_KrQDL2pebAJolgCOza8ldg.f['2']++;__cov_KrQDL2pebAJolgCOza8ldg.s['6']++;var terms=nlp.sentence(a[0]).terms;__cov_KrQDL2pebAJolgCOza8ldg.s['7']++;terms_test(terms,a[1],t);});__cov_KrQDL2pebAJolgCOza8ldg.s['8']++;t.end();});
