
var __cov_ynRfxG6QEDYhC$KUBidMXg = (Function('return this'))();
if (!__cov_ynRfxG6QEDYhC$KUBidMXg.__coverage__) { __cov_ynRfxG6QEDYhC$KUBidMXg.__coverage__ = {}; }
__cov_ynRfxG6QEDYhC$KUBidMXg = __cov_ynRfxG6QEDYhC$KUBidMXg.__coverage__;
if (!(__cov_ynRfxG6QEDYhC$KUBidMXg['/Users/Work/www/Projects/nlp_compromise/test/unit_test/pronoun_test.js'])) {
   __cov_ynRfxG6QEDYhC$KUBidMXg['/Users/Work/www/Projects/nlp_compromise/test/unit_test/pronoun_test.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/unit_test/pronoun_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0},"b":{},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"(anonymous_1)","line":5,"loc":{"start":{"line":5,"column":17},"end":{"line":5,"column":29}}},"2":{"name":"(anonymous_2)","line":22,"loc":{"start":{"line":22,"column":12},"end":{"line":22,"column":25}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":31}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":45}},"4":{"start":{"line":5,"column":0},"end":{"line":27,"column":3}},"5":{"start":{"line":6,"column":2},"end":{"line":25,"column":5}},"6":{"start":{"line":23,"column":4},"end":{"line":23,"column":39}},"7":{"start":{"line":24,"column":4},"end":{"line":24,"column":33}},"8":{"start":{"line":26,"column":2},"end":{"line":26,"column":10}}},"branchMap":{}};
}
__cov_ynRfxG6QEDYhC$KUBidMXg = __cov_ynRfxG6QEDYhC$KUBidMXg['/Users/Work/www/Projects/nlp_compromise/test/unit_test/pronoun_test.js'];
__cov_ynRfxG6QEDYhC$KUBidMXg.s['1']++;var test=require('tape');__cov_ynRfxG6QEDYhC$KUBidMXg.s['2']++;var nlp=require('./lib/nlp');__cov_ynRfxG6QEDYhC$KUBidMXg.s['3']++;var str_test=require('./lib/fns').str_test;__cov_ynRfxG6QEDYhC$KUBidMXg.s['4']++;test('pronoun:',function(t){__cov_ynRfxG6QEDYhC$KUBidMXg.f['1']++;__cov_ynRfxG6QEDYhC$KUBidMXg.s['5']++;[['John','he'],['John Smith','he'],['Jane','she'],['turtle','it'],['turtles','they'],['Toronto','it'],['studying','it'],['horses','they'],['road bikes','they'],['NHL goaltenders','they'],['Tony Danza','he'],['Tanya Danza','she'],['Mrs. Tanya Danza','she'],['John G. Fishermore Institute','it'],['John Fisher & sons','it']].forEach(function(a){__cov_ynRfxG6QEDYhC$KUBidMXg.f['2']++;__cov_ynRfxG6QEDYhC$KUBidMXg.s['6']++;var str=nlp.noun(a[0]).pronoun();__cov_ynRfxG6QEDYhC$KUBidMXg.s['7']++;str_test(str,a[0],a[1],t);});__cov_ynRfxG6QEDYhC$KUBidMXg.s['8']++;t.end();});
