
var __cov_Vw1svvl9d7oifbjhY6rpDA = (Function('return this'))();
if (!__cov_Vw1svvl9d7oifbjhY6rpDA.__coverage__) { __cov_Vw1svvl9d7oifbjhY6rpDA.__coverage__ = {}; }
__cov_Vw1svvl9d7oifbjhY6rpDA = __cov_Vw1svvl9d7oifbjhY6rpDA.__coverage__;
if (!(__cov_Vw1svvl9d7oifbjhY6rpDA['/Users/Work/www/Projects/nlp_compromise/test/unit_test/question_test.js'])) {
   __cov_Vw1svvl9d7oifbjhY6rpDA['/Users/Work/www/Projects/nlp_compromise/test/unit_test/question_test.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/unit_test/question_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0},"b":{},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"(anonymous_1)","line":5,"loc":{"start":{"line":5,"column":24},"end":{"line":5,"column":36}}},"2":{"name":"(anonymous_2)","line":16,"loc":{"start":{"line":16,"column":12},"end":{"line":16,"column":24}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":31}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":45}},"4":{"start":{"line":5,"column":0},"end":{"line":21,"column":3}},"5":{"start":{"line":6,"column":2},"end":{"line":19,"column":5}},"6":{"start":{"line":17,"column":4},"end":{"line":17,"column":40}},"7":{"start":{"line":18,"column":4},"end":{"line":18,"column":33}},"8":{"start":{"line":20,"column":2},"end":{"line":20,"column":10}}},"branchMap":{}};
}
__cov_Vw1svvl9d7oifbjhY6rpDA = __cov_Vw1svvl9d7oifbjhY6rpDA['/Users/Work/www/Projects/nlp_compromise/test/unit_test/question_test.js'];
__cov_Vw1svvl9d7oifbjhY6rpDA.s['1']++;var test=require('tape');__cov_Vw1svvl9d7oifbjhY6rpDA.s['2']++;var nlp=require('./lib/nlp');__cov_Vw1svvl9d7oifbjhY6rpDA.s['3']++;var str_test=require('./lib/fns').str_test;__cov_Vw1svvl9d7oifbjhY6rpDA.s['4']++;test('question-test :',function(t){__cov_Vw1svvl9d7oifbjhY6rpDA.f['1']++;__cov_Vw1svvl9d7oifbjhY6rpDA.s['5']++;[['which party was it?','which'],['which day was it?','when'],['but who did you go with?','who'],['what time did you show up?','when'],[`why'd you come so early?`,'why'],[`when'll you show up?`,'when'],[`is it fun?`,'yesNo'],[`was it fun?`,'yesNo'],[`did you think it was fun?`,'yesNo']].forEach(function(a){__cov_Vw1svvl9d7oifbjhY6rpDA.f['2']++;__cov_Vw1svvl9d7oifbjhY6rpDA.s['6']++;var str=nlp.question(a[0]).form();__cov_Vw1svvl9d7oifbjhY6rpDA.s['7']++;str_test(str,a[0],a[1],t);});__cov_Vw1svvl9d7oifbjhY6rpDA.s['8']++;t.end();});
