
var __cov_8kE15DYfnGsp_zC3I7dFtQ = (Function('return this'))();
if (!__cov_8kE15DYfnGsp_zC3I7dFtQ.__coverage__) { __cov_8kE15DYfnGsp_zC3I7dFtQ.__coverage__ = {}; }
__cov_8kE15DYfnGsp_zC3I7dFtQ = __cov_8kE15DYfnGsp_zC3I7dFtQ.__coverage__;
if (!(__cov_8kE15DYfnGsp_zC3I7dFtQ['/Users/Work/www/Projects/nlp_compromise/test/unit_test/quotation_test.js'])) {
   __cov_8kE15DYfnGsp_zC3I7dFtQ['/Users/Work/www/Projects/nlp_compromise/test/unit_test/quotation_test.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/unit_test/quotation_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0},"b":{"1":[0,0]},"f":{"1":0,"2":0,"3":0},"fnMap":{"1":{"name":"(anonymous_1)","line":5,"loc":{"start":{"line":5,"column":21},"end":{"line":5,"column":33}}},"2":{"name":"(anonymous_2)","line":15,"loc":{"start":{"line":15,"column":24},"end":{"line":15,"column":36}}},"3":{"name":"(anonymous_3)","line":23,"loc":{"start":{"line":23,"column":12},"end":{"line":23,"column":25}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":31}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":45}},"4":{"start":{"line":5,"column":0},"end":{"line":13,"column":2}},"5":{"start":{"line":6,"column":2},"end":{"line":6,"column":15}},"6":{"start":{"line":7,"column":2},"end":{"line":11,"column":3}},"7":{"start":{"line":8,"column":4},"end":{"line":10,"column":5}},"8":{"start":{"line":9,"column":6},"end":{"line":9,"column":37}},"9":{"start":{"line":12,"column":2},"end":{"line":12,"column":20}},"10":{"start":{"line":15,"column":0},"end":{"line":28,"column":3}},"11":{"start":{"line":16,"column":2},"end":{"line":26,"column":5}},"12":{"start":{"line":24,"column":4},"end":{"line":24,"column":49}},"13":{"start":{"line":25,"column":4},"end":{"line":25,"column":33}},"14":{"start":{"line":27,"column":2},"end":{"line":27,"column":10}}},"branchMap":{"1":{"line":8,"type":"if","locations":[{"start":{"line":8,"column":4},"end":{"line":8,"column":4}},{"start":{"line":8,"column":4},"end":{"line":8,"column":4}}]}}};
}
__cov_8kE15DYfnGsp_zC3I7dFtQ = __cov_8kE15DYfnGsp_zC3I7dFtQ['/Users/Work/www/Projects/nlp_compromise/test/unit_test/quotation_test.js'];
__cov_8kE15DYfnGsp_zC3I7dFtQ.s['1']++;var test=require('tape');__cov_8kE15DYfnGsp_zC3I7dFtQ.s['2']++;var nlp=require('./lib/nlp');__cov_8kE15DYfnGsp_zC3I7dFtQ.s['3']++;var str_test=require('./lib/fns').str_test;__cov_8kE15DYfnGsp_zC3I7dFtQ.s['4']++;var all_quotations=function(s){__cov_8kE15DYfnGsp_zC3I7dFtQ.f['1']++;__cov_8kE15DYfnGsp_zC3I7dFtQ.s['5']++;var str='';__cov_8kE15DYfnGsp_zC3I7dFtQ.s['6']++;for(var i=0;i<s.terms.length;i++){__cov_8kE15DYfnGsp_zC3I7dFtQ.s['7']++;if(s.terms[i].pos.Quotation){__cov_8kE15DYfnGsp_zC3I7dFtQ.b['1'][0]++;__cov_8kE15DYfnGsp_zC3I7dFtQ.s['8']++;str+=' '+s.terms[i].normal;}else{__cov_8kE15DYfnGsp_zC3I7dFtQ.b['1'][1]++;}}__cov_8kE15DYfnGsp_zC3I7dFtQ.s['9']++;return str.trim();};__cov_8kE15DYfnGsp_zC3I7dFtQ.s['10']++;test('quotation test:',function(t){__cov_8kE15DYfnGsp_zC3I7dFtQ.f['2']++;__cov_8kE15DYfnGsp_zC3I7dFtQ.s['11']++;[[`he is "really good"`,`really good`],[`he is "really good" i guess`,`really good`],[`he is "good" i guess`,`good`],[`he is "completely and utterly great" i guess`,`completely and utterly great`],[`“quote”`,`quote`],[`“quote is here”`,`quote is here`]].forEach(function(a){__cov_8kE15DYfnGsp_zC3I7dFtQ.f['3']++;__cov_8kE15DYfnGsp_zC3I7dFtQ.s['12']++;var str=all_quotations(nlp.sentence(a[0]));__cov_8kE15DYfnGsp_zC3I7dFtQ.s['13']++;str_test(str,a[0],a[1],t);});__cov_8kE15DYfnGsp_zC3I7dFtQ.s['14']++;t.end();});
