
var __cov_ch67PIKStSIggnx2SRkXLA = (Function('return this'))();
if (!__cov_ch67PIKStSIggnx2SRkXLA.__coverage__) { __cov_ch67PIKStSIggnx2SRkXLA.__coverage__ = {}; }
__cov_ch67PIKStSIggnx2SRkXLA = __cov_ch67PIKStSIggnx2SRkXLA.__coverage__;
if (!(__cov_ch67PIKStSIggnx2SRkXLA['/Users/Work/www/Projects/nlp_compromise/test/unit_test/replace_test.js'])) {
   __cov_ch67PIKStSIggnx2SRkXLA['/Users/Work/www/Projects/nlp_compromise/test/unit_test/replace_test.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/unit_test/replace_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0},"b":{},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"(anonymous_1)","line":6,"loc":{"start":{"line":6,"column":24},"end":{"line":6,"column":36}}},"2":{"name":"(anonymous_2)","line":13,"loc":{"start":{"line":13,"column":12},"end":{"line":13,"column":24}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":31}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":45}},"4":{"start":{"line":6,"column":0},"end":{"line":18,"column":3}},"5":{"start":{"line":7,"column":2},"end":{"line":16,"column":5}},"6":{"start":{"line":14,"column":4},"end":{"line":14,"column":60}},"7":{"start":{"line":15,"column":4},"end":{"line":15,"column":33}},"8":{"start":{"line":17,"column":2},"end":{"line":17,"column":10}}},"branchMap":{}};
}
__cov_ch67PIKStSIggnx2SRkXLA = __cov_ch67PIKStSIggnx2SRkXLA['/Users/Work/www/Projects/nlp_compromise/test/unit_test/replace_test.js'];
__cov_ch67PIKStSIggnx2SRkXLA.s['1']++;var test=require('tape');__cov_ch67PIKStSIggnx2SRkXLA.s['2']++;var nlp=require('./lib/nlp');__cov_ch67PIKStSIggnx2SRkXLA.s['3']++;var str_test=require('./lib/fns').str_test;__cov_ch67PIKStSIggnx2SRkXLA.s['4']++;test('match-replace :',function(t){__cov_ch67PIKStSIggnx2SRkXLA.f['1']++;__cov_ch67PIKStSIggnx2SRkXLA.s['5']++;[['the dog played','the dog','the cat','the cat played'],['the dog played','the [Noun]','the cat','the cat played'],['the dog played','the (dog|hamster|pet-snake)','the cat','the cat played'],['the boy and the girl','the [Noun]','the house','the house and the house'],['the boy and the girl','the cat','the house','the boy and the girl']].forEach(function(a){__cov_ch67PIKStSIggnx2SRkXLA.f['2']++;__cov_ch67PIKStSIggnx2SRkXLA.s['6']++;var str=nlp.sentence(a[0]).replace(a[1],a[2]).text();__cov_ch67PIKStSIggnx2SRkXLA.s['7']++;str_test(str,a[0],a[3],t);});__cov_ch67PIKStSIggnx2SRkXLA.s['8']++;t.end();});
