
var __cov_xR4FcxLMiYBQvwa7DETRZQ = (Function('return this'))();
if (!__cov_xR4FcxLMiYBQvwa7DETRZQ.__coverage__) { __cov_xR4FcxLMiYBQvwa7DETRZQ.__coverage__ = {}; }
__cov_xR4FcxLMiYBQvwa7DETRZQ = __cov_xR4FcxLMiYBQvwa7DETRZQ.__coverage__;
if (!(__cov_xR4FcxLMiYBQvwa7DETRZQ['/Users/Work/www/Projects/nlp_compromise/test/unit_test/sentence_type_test.js'])) {
   __cov_xR4FcxLMiYBQvwa7DETRZQ['/Users/Work/www/Projects/nlp_compromise/test/unit_test/sentence_type_test.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/unit_test/sentence_type_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0},"b":{},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"(anonymous_1)","line":5,"loc":{"start":{"line":5,"column":29},"end":{"line":5,"column":41}}},"2":{"name":"(anonymous_2)","line":11,"loc":{"start":{"line":11,"column":12},"end":{"line":11,"column":24}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":31}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":45}},"4":{"start":{"line":5,"column":0},"end":{"line":16,"column":3}},"5":{"start":{"line":6,"column":2},"end":{"line":14,"column":5}},"6":{"start":{"line":12,"column":4},"end":{"line":12,"column":55}},"7":{"start":{"line":13,"column":4},"end":{"line":13,"column":33}},"8":{"start":{"line":15,"column":2},"end":{"line":15,"column":10}}},"branchMap":{}};
}
__cov_xR4FcxLMiYBQvwa7DETRZQ = __cov_xR4FcxLMiYBQvwa7DETRZQ['/Users/Work/www/Projects/nlp_compromise/test/unit_test/sentence_type_test.js'];
__cov_xR4FcxLMiYBQvwa7DETRZQ.s['1']++;var test=require('tape');__cov_xR4FcxLMiYBQvwa7DETRZQ.s['2']++;var nlp=require('./lib/nlp');__cov_xR4FcxLMiYBQvwa7DETRZQ.s['3']++;var str_test=require('./lib/fns').str_test;__cov_xR4FcxLMiYBQvwa7DETRZQ.s['4']++;test('sentence-terminator:',function(t){__cov_xR4FcxLMiYBQvwa7DETRZQ.f['1']++;__cov_xR4FcxLMiYBQvwa7DETRZQ.s['5']++;[['Tony is nice.','.'],['Tony is nice!','!'],['Is Tony is nice?','?'],['Tony is okay','']].forEach(function(a){__cov_xR4FcxLMiYBQvwa7DETRZQ.f['2']++;__cov_xR4FcxLMiYBQvwa7DETRZQ.s['6']++;var str=nlp.text(a[0]).sentences[0].terminator();__cov_xR4FcxLMiYBQvwa7DETRZQ.s['7']++;str_test(str,a[0],a[1],t);});__cov_xR4FcxLMiYBQvwa7DETRZQ.s['8']++;t.end();});
