
var __cov_3yslfWh64RcGPrCfKB2iqQ = (Function('return this'))();
if (!__cov_3yslfWh64RcGPrCfKB2iqQ.__coverage__) { __cov_3yslfWh64RcGPrCfKB2iqQ.__coverage__ = {}; }
__cov_3yslfWh64RcGPrCfKB2iqQ = __cov_3yslfWh64RcGPrCfKB2iqQ.__coverage__;
if (!(__cov_3yslfWh64RcGPrCfKB2iqQ['/Users/Work/www/Projects/nlp_compromise/test/unit_test/sentence_negate_test.js'])) {
   __cov_3yslfWh64RcGPrCfKB2iqQ['/Users/Work/www/Projects/nlp_compromise/test/unit_test/sentence_negate_test.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/unit_test/sentence_negate_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0},"b":{},"f":{"1":0,"2":0,"3":0,"4":0,"5":0},"fnMap":{"1":{"name":"(anonymous_1)","line":5,"loc":{"start":{"line":5,"column":21},"end":{"line":5,"column":33}}},"2":{"name":"(anonymous_2)","line":7,"loc":{"start":{"line":7,"column":20},"end":{"line":7,"column":32}}},"3":{"name":"(anonymous_3)","line":34,"loc":{"start":{"line":34,"column":14},"end":{"line":34,"column":27}}},"4":{"name":"(anonymous_4)","line":41,"loc":{"start":{"line":41,"column":32},"end":{"line":41,"column":44}}},"5":{"name":"(anonymous_5)","line":61,"loc":{"start":{"line":61,"column":14},"end":{"line":61,"column":27}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":31}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":45}},"4":{"start":{"line":5,"column":0},"end":{"line":67,"column":3}},"5":{"start":{"line":7,"column":2},"end":{"line":39,"column":5}},"6":{"start":{"line":8,"column":4},"end":{"line":37,"column":7}},"7":{"start":{"line":35,"column":6},"end":{"line":35,"column":52}},"8":{"start":{"line":36,"column":6},"end":{"line":36,"column":35}},"9":{"start":{"line":38,"column":4},"end":{"line":38,"column":12}},"10":{"start":{"line":41,"column":2},"end":{"line":66,"column":5}},"11":{"start":{"line":42,"column":4},"end":{"line":64,"column":7}},"12":{"start":{"line":62,"column":6},"end":{"line":62,"column":52}},"13":{"start":{"line":63,"column":6},"end":{"line":63,"column":35}},"14":{"start":{"line":65,"column":4},"end":{"line":65,"column":12}}},"branchMap":{}};
}
__cov_3yslfWh64RcGPrCfKB2iqQ = __cov_3yslfWh64RcGPrCfKB2iqQ['/Users/Work/www/Projects/nlp_compromise/test/unit_test/sentence_negate_test.js'];
__cov_3yslfWh64RcGPrCfKB2iqQ.s['1']++;var test=require('tape');__cov_3yslfWh64RcGPrCfKB2iqQ.s['2']++;var nlp=require('./lib/nlp');__cov_3yslfWh64RcGPrCfKB2iqQ.s['3']++;var str_test=require('./lib/fns').str_test;__cov_3yslfWh64RcGPrCfKB2iqQ.s['4']++;test('==negation==',function(T){__cov_3yslfWh64RcGPrCfKB2iqQ.f['1']++;__cov_3yslfWh64RcGPrCfKB2iqQ.s['5']++;T.test('negate:',function(t){__cov_3yslfWh64RcGPrCfKB2iqQ.f['2']++;__cov_3yslfWh64RcGPrCfKB2iqQ.s['6']++;[[`john is good`,`john isn't good`],[`they are good`,`they aren't good`],[`they will be good`,`they won't be good`],[`he walks`,`he doesn't walk`],[`he walked`,`he didn't walk`],[`he has walked`,`he hasn't walked`],[`he will have walked`,`he won't have walked`],[`he is walking`,`he isn't walking`],[`i like running`,`i don't like running`],[`they swim`,`they don't swim`],[`we enjoy playing`,`we don't enjoy playing`],[`we don't swim`,`we do swim`],[`i don't care`,`i do care`],[`they don't care`,`they do care`],[`apples are not bad`,`apples are bad`],[`he does not like it`,`he does like it`],[`have not died yet`,`have died yet`],['john always walks','john never walks'],['john always walks quickly','john never walks quickly'],['everybody walks quickly','nobody walks quickly']].forEach(function(a){__cov_3yslfWh64RcGPrCfKB2iqQ.f['3']++;__cov_3yslfWh64RcGPrCfKB2iqQ.s['7']++;var str=nlp.statement(a[0]).negate().text();__cov_3yslfWh64RcGPrCfKB2iqQ.s['8']++;str_test(str,a[0],a[1],t);});__cov_3yslfWh64RcGPrCfKB2iqQ.s['9']++;t.end();});__cov_3yslfWh64RcGPrCfKB2iqQ.s['10']++;T.test('sentence un-negate:',function(t){__cov_3yslfWh64RcGPrCfKB2iqQ.f['4']++;__cov_3yslfWh64RcGPrCfKB2iqQ.s['11']++;[[`john isn't good`,`john is good`],[`they aren't good`,`they are good`],[`they won't be good`,`they will be good`],[`he didn't walk`,`he did walk`],[`he doesn't walk`,`he does walk`],[`he hasn't walked`,`he has walked`],[`he won't have walked`,`he will have walked`],[`he isn't walking`,`he is walking`],['john always walks','john never walks'],['john always walks quickly','john never walks quickly']].forEach(function(a){__cov_3yslfWh64RcGPrCfKB2iqQ.f['5']++;__cov_3yslfWh64RcGPrCfKB2iqQ.s['12']++;var str=nlp.statement(a[0]).negate().text();__cov_3yslfWh64RcGPrCfKB2iqQ.s['13']++;str_test(str,a[0],a[1],t);});__cov_3yslfWh64RcGPrCfKB2iqQ.s['14']++;t.end();});});
