
var __cov_5gMMCXeoJMYkseuh7xcf_Q = (Function('return this'))();
if (!__cov_5gMMCXeoJMYkseuh7xcf_Q.__coverage__) { __cov_5gMMCXeoJMYkseuh7xcf_Q.__coverage__ = {}; }
__cov_5gMMCXeoJMYkseuh7xcf_Q = __cov_5gMMCXeoJMYkseuh7xcf_Q.__coverage__;
if (!(__cov_5gMMCXeoJMYkseuh7xcf_Q['/Users/Work/www/Projects/nlp_compromise/test/unit_test/tagger_test.js'])) {
   __cov_5gMMCXeoJMYkseuh7xcf_Q['/Users/Work/www/Projects/nlp_compromise/test/unit_test/tagger_test.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/unit_test/tagger_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"b":{},"f":{"1":0,"2":0,"3":0},"fnMap":{"1":{"name":"(anonymous_1)","line":5,"loc":{"start":{"line":5,"column":17},"end":{"line":5,"column":29}}},"2":{"name":"(anonymous_2)","line":7,"loc":{"start":{"line":7,"column":27},"end":{"line":7,"column":39}}},"3":{"name":"(anonymous_3)","line":59,"loc":{"start":{"line":59,"column":14},"end":{"line":59,"column":27}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":31}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":45}},"4":{"start":{"line":5,"column":0},"end":{"line":65,"column":3}},"5":{"start":{"line":7,"column":2},"end":{"line":64,"column":5}},"6":{"start":{"line":8,"column":4},"end":{"line":62,"column":7}},"7":{"start":{"line":60,"column":6},"end":{"line":60,"column":43}},"8":{"start":{"line":61,"column":6},"end":{"line":61,"column":31}},"9":{"start":{"line":63,"column":4},"end":{"line":63,"column":12}}},"branchMap":{}};
}
__cov_5gMMCXeoJMYkseuh7xcf_Q = __cov_5gMMCXeoJMYkseuh7xcf_Q['/Users/Work/www/Projects/nlp_compromise/test/unit_test/tagger_test.js'];
__cov_5gMMCXeoJMYkseuh7xcf_Q.s['1']++;var test=require('tape');__cov_5gMMCXeoJMYkseuh7xcf_Q.s['2']++;var nlp=require('./lib/nlp');__cov_5gMMCXeoJMYkseuh7xcf_Q.s['3']++;var pos_test=require('./lib/fns').pos_test;__cov_5gMMCXeoJMYkseuh7xcf_Q.s['4']++;test('=Tagger=',function(T){__cov_5gMMCXeoJMYkseuh7xcf_Q.f['1']++;__cov_5gMMCXeoJMYkseuh7xcf_Q.s['5']++;T.test('pos-basic-tag:',function(t){__cov_5gMMCXeoJMYkseuh7xcf_Q.f['2']++;__cov_5gMMCXeoJMYkseuh7xcf_Q.s['6']++;[['John is pretty',['Person','Copula','Adjective']],['John was lofty',['Person','Copula','Adjective']],['John Smith was lofty',['Person','Copula','Adjective']],['asdfes was lofty',['Noun','Copula','Adjective']],['asdfes lksejfj was lofty',['Noun','Copula','Adjective']],['Spencer Kelly is in Canada',['Person','Copula','Preposition','Place']],['He is in Canada',['Pronoun','Copula','Preposition','Place']],['5 red roses',['Value','Adjective','Noun']],['walk the walk',['Verb','Determiner','Noun']],['Peter the man',['Person','Determiner','Noun']],['book the flight',['Verb','Determiner','Noun']],['u r nice',['Pronoun','Copula','Adjective']],['canadian bacon',['Demonym','Noun']],['canadian dollar',['Currency']],['bill lkjsdf\'s',['Person']],['bill lkjsdf\'s house',['Person','Noun']],['Bill Lkjsdf\'s house',['Person','Noun']],['Bill Lkjsdf\'s House',['Person','Noun']],['who is good?',['Question','Copula','Adjective']],['which is good?',['Question','Copula','Adjective']],['bacon which is good',['Noun','Pronoun','Copula','Adjective']],['bacon which really is good',['Noun','Pronoun','Adverb','Copula','Adjective']],['Douglas who really is good',['Person','Pronoun','Adverb','Copula','Adjective']],['lkj@fun.com',['Email']],['j@f.ti',['Email']],['j@ti',['Noun']],['@ti',['AtMention']],['#funtimes',['HashTag']],['http://fun.com/cool?fun=yes',['Url']],['#cool fun.com @cooman',['HashTag','Url','AtMention']],['John swim',['Person','Verb']],['John Swim',['Person','Verb']],['John, John',['Person','Person']],['John, you',['Person','Pronoun']],['John you',['Person','Pronoun']],['you John you',['Pronoun','Person','Pronoun']],['10 + 9',['Value','Symbol','Value']],['2 * 90 = 180',['Value','Symbol','Value','Symbol','Value']],['one - seventy-six',['Value','Symbol','Value']]].forEach(function(a){__cov_5gMMCXeoJMYkseuh7xcf_Q.f['3']++;__cov_5gMMCXeoJMYkseuh7xcf_Q.s['7']++;var terms=nlp.sentence(a[0]).terms;__cov_5gMMCXeoJMYkseuh7xcf_Q.s['8']++;pos_test(terms,a[1],t);});__cov_5gMMCXeoJMYkseuh7xcf_Q.s['9']++;t.end();});});
