
var __cov_KEKN5XGDWzIuqest4qhYng = (Function('return this'))();
if (!__cov_KEKN5XGDWzIuqest4qhYng.__coverage__) { __cov_KEKN5XGDWzIuqest4qhYng.__coverage__ = {}; }
__cov_KEKN5XGDWzIuqest4qhYng = __cov_KEKN5XGDWzIuqest4qhYng.__coverage__;
if (!(__cov_KEKN5XGDWzIuqest4qhYng['/Users/Work/www/Projects/nlp_compromise/test/unit_test/tense_test.js'])) {
   __cov_KEKN5XGDWzIuqest4qhYng['/Users/Work/www/Projects/nlp_compromise/test/unit_test/tense_test.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/unit_test/tense_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0},"b":{},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"(anonymous_1)","line":5,"loc":{"start":{"line":5,"column":31},"end":{"line":5,"column":43}}},"2":{"name":"(anonymous_2)","line":28,"loc":{"start":{"line":28,"column":12},"end":{"line":28,"column":25}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":31}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":45}},"4":{"start":{"line":5,"column":0},"end":{"line":42,"column":3}},"5":{"start":{"line":6,"column":2},"end":{"line":40,"column":5}},"6":{"start":{"line":29,"column":4},"end":{"line":29,"column":27}},"7":{"start":{"line":31,"column":4},"end":{"line":31,"column":16}},"8":{"start":{"line":32,"column":4},"end":{"line":32,"column":38}},"9":{"start":{"line":34,"column":4},"end":{"line":34,"column":18}},"10":{"start":{"line":35,"column":4},"end":{"line":35,"column":38}},"11":{"start":{"line":37,"column":4},"end":{"line":37,"column":19}},"12":{"start":{"line":38,"column":4},"end":{"line":38,"column":38}},"13":{"start":{"line":41,"column":2},"end":{"line":41,"column":10}}},"branchMap":{}};
}
__cov_KEKN5XGDWzIuqest4qhYng = __cov_KEKN5XGDWzIuqest4qhYng['/Users/Work/www/Projects/nlp_compromise/test/unit_test/tense_test.js'];
__cov_KEKN5XGDWzIuqest4qhYng.s['1']++;var test=require('tape');__cov_KEKN5XGDWzIuqest4qhYng.s['2']++;var nlp=require('./lib/nlp');__cov_KEKN5XGDWzIuqest4qhYng.s['3']++;var str_test=require('./lib/fns').str_test;__cov_KEKN5XGDWzIuqest4qhYng.s['4']++;test('sentence-change-tense:',function(t){__cov_KEKN5XGDWzIuqest4qhYng.f['1']++;__cov_KEKN5XGDWzIuqest4qhYng.s['5']++;[['john walks quickly','john walked quickly','john will walk quickly'],['he is quick','he was quick','he will be quick'],['the stool falls over','the stool fell over','the stool will fall over'],['he finishes first','he finished first','he will finish first'],['our house looks great','our house looked great','our house will look great'],['he does what he can to stop','he did what he could to stop','he will do what he can to stop'],['goes to sleep','went to sleep','will go to sleep'],['this is one sentence. This makes two now.','this was one sentence. This made two now.','this will be one sentence. This will make two now.']].forEach(function(a){__cov_KEKN5XGDWzIuqest4qhYng.f['2']++;__cov_KEKN5XGDWzIuqest4qhYng.s['6']++;var s=nlp.text(a[0]);__cov_KEKN5XGDWzIuqest4qhYng.s['7']++;s.to_past();__cov_KEKN5XGDWzIuqest4qhYng.s['8']++;str_test(s.text(),a[0],a[1],t);__cov_KEKN5XGDWzIuqest4qhYng.s['9']++;s.to_future();__cov_KEKN5XGDWzIuqest4qhYng.s['10']++;str_test(s.text(),a[0],a[2],t);__cov_KEKN5XGDWzIuqest4qhYng.s['11']++;s.to_present();__cov_KEKN5XGDWzIuqest4qhYng.s['12']++;str_test(s.text(),a[0],a[0],t);});__cov_KEKN5XGDWzIuqest4qhYng.s['13']++;t.end();});
