
var __cov_RevUOE_Wb4uqARO21WnKsQ = (Function('return this'))();
if (!__cov_RevUOE_Wb4uqARO21WnKsQ.__coverage__) { __cov_RevUOE_Wb4uqARO21WnKsQ.__coverage__ = {}; }
__cov_RevUOE_Wb4uqARO21WnKsQ = __cov_RevUOE_Wb4uqARO21WnKsQ.__coverage__;
if (!(__cov_RevUOE_Wb4uqARO21WnKsQ['/Users/Work/www/Projects/nlp_compromise/test/unit_test/term_negate_test.js'])) {
   __cov_RevUOE_Wb4uqARO21WnKsQ['/Users/Work/www/Projects/nlp_compromise/test/unit_test/term_negate_test.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/unit_test/term_negate_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0},"b":{},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"(anonymous_1)","line":6,"loc":{"start":{"line":6,"column":21},"end":{"line":6,"column":33}}},"2":{"name":"(anonymous_2)","line":27,"loc":{"start":{"line":27,"column":12},"end":{"line":27,"column":24}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":31}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":45}},"4":{"start":{"line":6,"column":0},"end":{"line":32,"column":3}},"5":{"start":{"line":7,"column":2},"end":{"line":30,"column":5}},"6":{"start":{"line":28,"column":4},"end":{"line":28,"column":45}},"7":{"start":{"line":29,"column":4},"end":{"line":29,"column":33}},"8":{"start":{"line":31,"column":2},"end":{"line":31,"column":10}}},"branchMap":{}};
}
__cov_RevUOE_Wb4uqARO21WnKsQ = __cov_RevUOE_Wb4uqARO21WnKsQ['/Users/Work/www/Projects/nlp_compromise/test/unit_test/term_negate_test.js'];
__cov_RevUOE_Wb4uqARO21WnKsQ.s['1']++;var test=require('tape');__cov_RevUOE_Wb4uqARO21WnKsQ.s['2']++;var nlp=require('./lib/nlp');__cov_RevUOE_Wb4uqARO21WnKsQ.s['3']++;var str_test=require('./lib/fns').str_test;__cov_RevUOE_Wb4uqARO21WnKsQ.s['4']++;test('term negate:',function(t){__cov_RevUOE_Wb4uqARO21WnKsQ.f['1']++;__cov_RevUOE_Wb4uqARO21WnKsQ.s['5']++;[['is','isn\'t'],['will','won\'t'],['will be','won\'t be'],['was','wasn\'t'],['walks','doesn\'t walk'],['walked','didn\'t walk'],['walking','not walking'],['walk','don\'t walk'],['will walk','won\'t walk'],['will have walked','won\'t have walked'],['corrupted','didn\'t corrupt'],['jumped','didn\'t jump'],['stunk up','didn\'t stink up'],[`would study`,`wouldn't study`],[`could study`,`couldn't study`],[`should study`,`shouldn't study`]].forEach(function(a){__cov_RevUOE_Wb4uqARO21WnKsQ.f['2']++;__cov_RevUOE_Wb4uqARO21WnKsQ.s['6']++;var str=nlp.verb(a[0]).negate().normal;__cov_RevUOE_Wb4uqARO21WnKsQ.s['7']++;str_test(str,a[0],a[1],t);});__cov_RevUOE_Wb4uqARO21WnKsQ.s['8']++;t.end();});
