
var __cov_DzYaytrMaLu0LQGt_n5FuA = (Function('return this'))();
if (!__cov_DzYaytrMaLu0LQGt_n5FuA.__coverage__) { __cov_DzYaytrMaLu0LQGt_n5FuA.__coverage__ = {}; }
__cov_DzYaytrMaLu0LQGt_n5FuA = __cov_DzYaytrMaLu0LQGt_n5FuA.__coverage__;
if (!(__cov_DzYaytrMaLu0LQGt_n5FuA['/Users/Work/www/Projects/nlp_compromise/test/unit_test/topics_test.js'])) {
   __cov_DzYaytrMaLu0LQGt_n5FuA['/Users/Work/www/Projects/nlp_compromise/test/unit_test/topics_test.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/unit_test/topics_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0},"b":{},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"(anonymous_1)","line":5,"loc":{"start":{"line":5,"column":16},"end":{"line":5,"column":28}}},"2":{"name":"(anonymous_2)","line":12,"loc":{"start":{"line":12,"column":12},"end":{"line":12,"column":25}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":31}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":45}},"4":{"start":{"line":5,"column":0},"end":{"line":17,"column":3}},"5":{"start":{"line":6,"column":2},"end":{"line":15,"column":5}},"6":{"start":{"line":13,"column":4},"end":{"line":13,"column":46}},"7":{"start":{"line":14,"column":4},"end":{"line":14,"column":33}},"8":{"start":{"line":16,"column":2},"end":{"line":16,"column":10}}},"branchMap":{}};
}
__cov_DzYaytrMaLu0LQGt_n5FuA = __cov_DzYaytrMaLu0LQGt_n5FuA['/Users/Work/www/Projects/nlp_compromise/test/unit_test/topics_test.js'];
__cov_DzYaytrMaLu0LQGt_n5FuA.s['1']++;var test=require('tape');__cov_DzYaytrMaLu0LQGt_n5FuA.s['2']++;var nlp=require('./lib/nlp');__cov_DzYaytrMaLu0LQGt_n5FuA.s['3']++;var str_test=require('./lib/fns').str_test;__cov_DzYaytrMaLu0LQGt_n5FuA.s['4']++;test('topics:',function(t){__cov_DzYaytrMaLu0LQGt_n5FuA.f['1']++;__cov_DzYaytrMaLu0LQGt_n5FuA.s['5']++;[['James and Tony Hawk both live in Toronto. Tony Hawk is cool.','tony hawk'],['I live Toronto. I think Toronto is cool.','toronto'],['The EACD united in 1972. EACD must follow regulations.','eacd'],['The Elkjsdflkjsdf sells hamburgers. I think the Elkjsdflkjsdf eats turky.','elkjsdflkjsdf'],['Toronto\'s citizens love toronto!','toronto']].forEach(function(a){__cov_DzYaytrMaLu0LQGt_n5FuA.f['2']++;__cov_DzYaytrMaLu0LQGt_n5FuA.s['6']++;var str=nlp.text(a[0]).topics()[0].text;__cov_DzYaytrMaLu0LQGt_n5FuA.s['7']++;str_test(str,a[0],a[1],t);});__cov_DzYaytrMaLu0LQGt_n5FuA.s['8']++;t.end();});
