
var __cov_3X$OXBUS9dFKQheZIOzpTQ = (Function('return this'))();
if (!__cov_3X$OXBUS9dFKQheZIOzpTQ.__coverage__) { __cov_3X$OXBUS9dFKQheZIOzpTQ.__coverage__ = {}; }
__cov_3X$OXBUS9dFKQheZIOzpTQ = __cov_3X$OXBUS9dFKQheZIOzpTQ.__coverage__;
if (!(__cov_3X$OXBUS9dFKQheZIOzpTQ['/Users/Work/www/Projects/nlp_compromise/test/unit_test/verb_to_adjective_test.js'])) {
   __cov_3X$OXBUS9dFKQheZIOzpTQ['/Users/Work/www/Projects/nlp_compromise/test/unit_test/verb_to_adjective_test.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/unit_test/verb_to_adjective_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0},"b":{},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"(anonymous_1)","line":6,"loc":{"start":{"line":6,"column":27},"end":{"line":6,"column":39}}},"2":{"name":"(anonymous_2)","line":13,"loc":{"start":{"line":13,"column":12},"end":{"line":13,"column":24}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":31}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":45}},"4":{"start":{"line":6,"column":0},"end":{"line":18,"column":3}},"5":{"start":{"line":7,"column":2},"end":{"line":16,"column":5}},"6":{"start":{"line":14,"column":4},"end":{"line":14,"column":44}},"7":{"start":{"line":15,"column":4},"end":{"line":15,"column":33}},"8":{"start":{"line":17,"column":2},"end":{"line":17,"column":10}}},"branchMap":{}};
}
__cov_3X$OXBUS9dFKQheZIOzpTQ = __cov_3X$OXBUS9dFKQheZIOzpTQ['/Users/Work/www/Projects/nlp_compromise/test/unit_test/verb_to_adjective_test.js'];
__cov_3X$OXBUS9dFKQheZIOzpTQ.s['1']++;var test=require('tape');__cov_3X$OXBUS9dFKQheZIOzpTQ.s['2']++;var nlp=require('./lib/nlp');__cov_3X$OXBUS9dFKQheZIOzpTQ.s['3']++;var str_test=require('./lib/fns').str_test;__cov_3X$OXBUS9dFKQheZIOzpTQ.s['4']++;test('verb-to-adjective:',function(t){__cov_3X$OXBUS9dFKQheZIOzpTQ.f['1']++;__cov_3X$OXBUS9dFKQheZIOzpTQ.s['5']++;[['walk','walkable'],['sing','singable'],['win','winnable'],['convert','convertible'],['see','visible']].forEach(function(a){__cov_3X$OXBUS9dFKQheZIOzpTQ.f['2']++;__cov_3X$OXBUS9dFKQheZIOzpTQ.s['6']++;var str=nlp.verb(a[0]).to_adjective();__cov_3X$OXBUS9dFKQheZIOzpTQ.s['7']++;str_test(str,a[0],a[1],t);});__cov_3X$OXBUS9dFKQheZIOzpTQ.s['8']++;t.end();});
