
var __cov_VaFmlUOUeBYCkasZ2vpNog = (Function('return this'))();
if (!__cov_VaFmlUOUeBYCkasZ2vpNog.__coverage__) { __cov_VaFmlUOUeBYCkasZ2vpNog.__coverage__ = {}; }
__cov_VaFmlUOUeBYCkasZ2vpNog = __cov_VaFmlUOUeBYCkasZ2vpNog.__coverage__;
if (!(__cov_VaFmlUOUeBYCkasZ2vpNog['/Users/Work/www/Projects/nlp_compromise/test/unit_test/wordcount_test.js'])) {
   __cov_VaFmlUOUeBYCkasZ2vpNog['/Users/Work/www/Projects/nlp_compromise/test/unit_test/wordcount_test.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/unit_test/wordcount_test.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0},"b":{},"f":{"1":0,"2":0,"3":0,"4":0,"5":0},"fnMap":{"1":{"name":"(anonymous_1)","line":5,"loc":{"start":{"line":5,"column":22},"end":{"line":5,"column":34}}},"2":{"name":"(anonymous_2)","line":7,"loc":{"start":{"line":7,"column":24},"end":{"line":7,"column":36}}},"3":{"name":"(anonymous_3)","line":15,"loc":{"start":{"line":15,"column":14},"end":{"line":15,"column":27}}},"4":{"name":"(anonymous_4)","line":22,"loc":{"start":{"line":22,"column":20},"end":{"line":22,"column":32}}},"5":{"name":"(anonymous_5)","line":30,"loc":{"start":{"line":30,"column":14},"end":{"line":30,"column":27}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},"2":{"start":{"line":2,"column":0},"end":{"line":2,"column":31}},"3":{"start":{"line":3,"column":0},"end":{"line":3,"column":45}},"4":{"start":{"line":5,"column":0},"end":{"line":37,"column":3}},"5":{"start":{"line":7,"column":2},"end":{"line":20,"column":5}},"6":{"start":{"line":8,"column":4},"end":{"line":18,"column":7}},"7":{"start":{"line":16,"column":6},"end":{"line":16,"column":48}},"8":{"start":{"line":17,"column":6},"end":{"line":17,"column":35}},"9":{"start":{"line":19,"column":4},"end":{"line":19,"column":12}},"10":{"start":{"line":22,"column":2},"end":{"line":35,"column":5}},"11":{"start":{"line":23,"column":4},"end":{"line":33,"column":7}},"12":{"start":{"line":31,"column":6},"end":{"line":31,"column":44}},"13":{"start":{"line":32,"column":6},"end":{"line":32,"column":35}},"14":{"start":{"line":34,"column":4},"end":{"line":34,"column":12}}},"branchMap":{}};
}
__cov_VaFmlUOUeBYCkasZ2vpNog = __cov_VaFmlUOUeBYCkasZ2vpNog['/Users/Work/www/Projects/nlp_compromise/test/unit_test/wordcount_test.js'];
__cov_VaFmlUOUeBYCkasZ2vpNog.s['1']++;var test=require('tape');__cov_VaFmlUOUeBYCkasZ2vpNog.s['2']++;var nlp=require('./lib/nlp');__cov_VaFmlUOUeBYCkasZ2vpNog.s['3']++;var str_test=require('./lib/fns').str_test;__cov_VaFmlUOUeBYCkasZ2vpNog.s['4']++;test('==WordCount==',function(T){__cov_VaFmlUOUeBYCkasZ2vpNog.f['1']++;__cov_VaFmlUOUeBYCkasZ2vpNog.s['5']++;T.test('sentence():',function(t){__cov_VaFmlUOUeBYCkasZ2vpNog.f['2']++;__cov_VaFmlUOUeBYCkasZ2vpNog.s['6']++;[['he is good',3],['jack and jill went up the hill.',7],['Mr. Clinton did so.',3],['Bill Clinton ate cheese.',3],['5kb of data.',3],['it was five hundred and seventy two.',3]].forEach(function(a){__cov_VaFmlUOUeBYCkasZ2vpNog.f['3']++;__cov_VaFmlUOUeBYCkasZ2vpNog.s['7']++;var num=nlp.sentence(a[0]).word_count();__cov_VaFmlUOUeBYCkasZ2vpNog.s['8']++;str_test(num,a[0],a[1],t);});__cov_VaFmlUOUeBYCkasZ2vpNog.s['9']++;t.end();});__cov_VaFmlUOUeBYCkasZ2vpNog.s['10']++;T.test('text():',function(t){__cov_VaFmlUOUeBYCkasZ2vpNog.f['4']++;__cov_VaFmlUOUeBYCkasZ2vpNog.s['11']++;[['he is good',3],['jack and jill went up the hill. They got water.',10],['Mr. Clinton did so.',3],['Bill Clinton ate cheese.',3],['Bill Clinton went walking',3],['Bill Clinton will go walking',3]].forEach(function(a){__cov_VaFmlUOUeBYCkasZ2vpNog.f['5']++;__cov_VaFmlUOUeBYCkasZ2vpNog.s['12']++;var num=nlp.text(a[0]).word_count();__cov_VaFmlUOUeBYCkasZ2vpNog.s['13']++;str_test(num,a[0],a[1],t);});__cov_VaFmlUOUeBYCkasZ2vpNog.s['14']++;t.end();});});
