
var __cov_ldHNLE8goLMBdVlpRN5MMw = (Function('return this'))();
if (!__cov_ldHNLE8goLMBdVlpRN5MMw.__coverage__) { __cov_ldHNLE8goLMBdVlpRN5MMw.__coverage__ = {}; }
__cov_ldHNLE8goLMBdVlpRN5MMw = __cov_ldHNLE8goLMBdVlpRN5MMw.__coverage__;
if (!(__cov_ldHNLE8goLMBdVlpRN5MMw['/Users/Work/www/Projects/nlp_compromise/test/prerelease/checklist.js'])) {
   __cov_ldHNLE8goLMBdVlpRN5MMw['/Users/Work/www/Projects/nlp_compromise/test/prerelease/checklist.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/prerelease/checklist.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"b":{},"f":{"1":0,"2":0},"fnMap":{"1":{"name":"(anonymous_1)","line":3,"loc":{"start":{"line":3,"column":16},"end":{"line":3,"column":36}}},"2":{"name":"(anonymous_2)","line":4,"loc":{"start":{"line":4,"column":13},"end":{"line":4,"column":25}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":1,"column":27}},"2":{"start":{"line":3,"column":0},"end":{"line":12,"column":2}},"3":{"start":{"line":4,"column":2},"end":{"line":11,"column":5}},"4":{"start":{"line":6,"column":4},"end":{"line":6,"column":64}},"5":{"start":{"line":7,"column":4},"end":{"line":7,"column":66}},"6":{"start":{"line":8,"column":4},"end":{"line":8,"column":59}},"7":{"start":{"line":9,"column":4},"end":{"line":9,"column":72}},"8":{"start":{"line":10,"column":4},"end":{"line":10,"column":12}},"9":{"start":{"line":13,"column":0},"end":{"line":13,"column":27}}},"branchMap":{}};
}
__cov_ldHNLE8goLMBdVlpRN5MMw = __cov_ldHNLE8goLMBdVlpRN5MMw['/Users/Work/www/Projects/nlp_compromise/test/prerelease/checklist.js'];
__cov_ldHNLE8goLMBdVlpRN5MMw.s['1']++;var test=require('tape');__cov_ldHNLE8goLMBdVlpRN5MMw.s['2']++;var checklist=function(nlp,desc){__cov_ldHNLE8goLMBdVlpRN5MMw.f['1']++;__cov_ldHNLE8goLMBdVlpRN5MMw.s['3']++;test(desc,function(t){__cov_ldHNLE8goLMBdVlpRN5MMw.f['2']++;__cov_ldHNLE8goLMBdVlpRN5MMw.s['4']++;var terms=nlp.text('john is good',{}).sentences[0].terms;__cov_ldHNLE8goLMBdVlpRN5MMw.s['5']++;t.equal(terms[0].pos.Person,true,'john is Person -'+desc);__cov_ldHNLE8goLMBdVlpRN5MMw.s['6']++;t.equal(terms[1].pos.Verb,true,'is - Verb -'+desc);__cov_ldHNLE8goLMBdVlpRN5MMw.s['7']++;t.equal(terms[2].pos.Adjective,true,'good is Adjective -'+desc);__cov_ldHNLE8goLMBdVlpRN5MMw.s['8']++;t.end();});};__cov_ldHNLE8goLMBdVlpRN5MMw.s['9']++;module.exports=checklist;
