"use strict";
var __cov_V7Cf6VnURoxfUcuCuODbKw = (Function('return this'))();
if (!__cov_V7Cf6VnURoxfUcuCuODbKw.__coverage__) { __cov_V7Cf6VnURoxfUcuCuODbKw.__coverage__ = {}; }
__cov_V7Cf6VnURoxfUcuCuODbKw = __cov_V7Cf6VnURoxfUcuCuODbKw.__coverage__;
if (!(__cov_V7Cf6VnURoxfUcuCuODbKw['/Users/Work/www/Projects/nlp_compromise/test/perf_tests/pos_test/fallback.js'])) {
   __cov_V7Cf6VnURoxfUcuCuODbKw['/Users/Work/www/Projects/nlp_compromise/test/perf_tests/pos_test/fallback.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/perf_tests/pos_test/fallback.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":0,"16":0,"17":0,"18":0,"19":0,"20":0},"b":{"1":[0,0],"2":[0,0],"3":[0,0]},"f":{"1":0},"fnMap":{"1":{"name":"(anonymous_1)","line":3,"loc":{"start":{"line":3,"column":17},"end":{"line":3,"column":32}}}},"statementMap":{"1":{"start":{"line":3,"column":0},"end":{"line":30,"column":2}},"2":{"start":{"line":4,"column":2},"end":{"line":4,"column":17}},"3":{"start":{"line":5,"column":2},"end":{"line":5,"column":16}},"4":{"start":{"line":6,"column":2},"end":{"line":15,"column":3}},"5":{"start":{"line":7,"column":4},"end":{"line":14,"column":5}},"6":{"start":{"line":8,"column":6},"end":{"line":8,"column":41}},"7":{"start":{"line":9,"column":6},"end":{"line":13,"column":7}},"8":{"start":{"line":10,"column":8},"end":{"line":10,"column":47}},"9":{"start":{"line":11,"column":8},"end":{"line":11,"column":29}},"10":{"start":{"line":12,"column":8},"end":{"line":12,"column":19}},"11":{"start":{"line":16,"column":2},"end":{"line":16,"column":15}},"12":{"start":{"line":17,"column":2},"end":{"line":20,"column":5}},"13":{"start":{"line":19,"column":4},"end":{"line":19,"column":28}},"14":{"start":{"line":21,"column":2},"end":{"line":26,"column":5}},"15":{"start":{"line":22,"column":4},"end":{"line":24,"column":5}},"16":{"start":{"line":23,"column":6},"end":{"line":23,"column":16}},"17":{"start":{"line":25,"column":4},"end":{"line":25,"column":13}},"18":{"start":{"line":27,"column":2},"end":{"line":27,"column":26}},"19":{"start":{"line":29,"column":2},"end":{"line":29,"column":13}},"20":{"start":{"line":32,"column":0},"end":{"line":32,"column":26}}},"branchMap":{"1":{"line":9,"type":"if","locations":[{"start":{"line":9,"column":6},"end":{"line":9,"column":6}},{"start":{"line":9,"column":6},"end":{"line":9,"column":6}}]},"2":{"line":10,"type":"binary-expr","locations":[{"start":{"line":10,"column":26},"end":{"line":10,"column":41}},{"start":{"line":10,"column":45},"end":{"line":10,"column":46}}]},"3":{"line":22,"type":"if","locations":[{"start":{"line":22,"column":4},"end":{"line":22,"column":4}},{"start":{"line":22,"column":4},"end":{"line":22,"column":4}}]}}};
}
__cov_V7Cf6VnURoxfUcuCuODbKw = __cov_V7Cf6VnURoxfUcuCuODbKw['/Users/Work/www/Projects/nlp_compromise/test/perf_tests/pos_test/fallback.js'];
__cov_V7Cf6VnURoxfUcuCuODbKw.s['1']++;const fallback=function(text){__cov_V7Cf6VnURoxfUcuCuODbKw.f['1']++;__cov_V7Cf6VnURoxfUcuCuODbKw.s['2']++;let nouns={};__cov_V7Cf6VnURoxfUcuCuODbKw.s['3']++;let count=0;__cov_V7Cf6VnURoxfUcuCuODbKw.s['4']++;for(let i=0;i<text.sentences.length;i++){__cov_V7Cf6VnURoxfUcuCuODbKw.s['5']++;for(let o=0;o<text.sentences[i].terms.length;o++){__cov_V7Cf6VnURoxfUcuCuODbKw.s['6']++;let t=text.sentences[i].terms[o];__cov_V7Cf6VnURoxfUcuCuODbKw.s['7']++;if(t.reason==='fallback'){__cov_V7Cf6VnURoxfUcuCuODbKw.b['1'][0]++;__cov_V7Cf6VnURoxfUcuCuODbKw.s['8']++;nouns[t.normal]=(__cov_V7Cf6VnURoxfUcuCuODbKw.b['2'][0]++,nouns[t.normal])||(__cov_V7Cf6VnURoxfUcuCuODbKw.b['2'][1]++,0);__cov_V7Cf6VnURoxfUcuCuODbKw.s['9']++;nouns[t.normal]+=1;__cov_V7Cf6VnURoxfUcuCuODbKw.s['10']++;count+=1;}else{__cov_V7Cf6VnURoxfUcuCuODbKw.b['1'][1]++;}}}__cov_V7Cf6VnURoxfUcuCuODbKw.s['11']++;let arr=[];__cov_V7Cf6VnURoxfUcuCuODbKw.s['12']++;Object.keys(nouns).forEach(k=>{__cov_V7Cf6VnURoxfUcuCuODbKw.s['13']++;arr.push([k,nouns[k]]);});__cov_V7Cf6VnURoxfUcuCuODbKw.s['14']++;arr=arr.sort((a,b)=>{__cov_V7Cf6VnURoxfUcuCuODbKw.s['15']++;if(a[1]>b[1]){__cov_V7Cf6VnURoxfUcuCuODbKw.b['3'][0]++;__cov_V7Cf6VnURoxfUcuCuODbKw.s['16']++;return-1;}else{__cov_V7Cf6VnURoxfUcuCuODbKw.b['3'][1]++;}__cov_V7Cf6VnURoxfUcuCuODbKw.s['17']++;return 1;});__cov_V7Cf6VnURoxfUcuCuODbKw.s['18']++;arr=arr.slice(0,150);__cov_V7Cf6VnURoxfUcuCuODbKw.s['19']++;return arr;};__cov_V7Cf6VnURoxfUcuCuODbKw.s['20']++;module.exports=fallback;
