"use strict";
var __cov_uFernoVyibfwDLJr3wZNbg = (Function('return this'))();
if (!__cov_uFernoVyibfwDLJr3wZNbg.__coverage__) { __cov_uFernoVyibfwDLJr3wZNbg.__coverage__ = {}; }
__cov_uFernoVyibfwDLJr3wZNbg = __cov_uFernoVyibfwDLJr3wZNbg.__coverage__;
if (!(__cov_uFernoVyibfwDLJr3wZNbg['/Users/Work/www/Projects/nlp_compromise/test/perf_tests/pos_test/reasons.js'])) {
   __cov_uFernoVyibfwDLJr3wZNbg['/Users/Work/www/Projects/nlp_compromise/test/perf_tests/pos_test/reasons.js'] = {"path":"/Users/Work/www/Projects/nlp_compromise/test/perf_tests/pos_test/reasons.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":0,"16":0,"17":0,"18":0,"19":0,"20":0,"21":0},"b":{"1":[0,0],"2":[0,0]},"f":{"1":0},"fnMap":{"1":{"name":"(anonymous_1)","line":3,"loc":{"start":{"line":3,"column":20},"end":{"line":3,"column":35}}}},"statementMap":{"1":{"start":{"line":3,"column":0},"end":{"line":27,"column":2}},"2":{"start":{"line":4,"column":2},"end":{"line":4,"column":19}},"3":{"start":{"line":5,"column":2},"end":{"line":5,"column":16}},"4":{"start":{"line":6,"column":2},"end":{"line":13,"column":3}},"5":{"start":{"line":7,"column":4},"end":{"line":12,"column":5}},"6":{"start":{"line":8,"column":6},"end":{"line":8,"column":48}},"7":{"start":{"line":9,"column":6},"end":{"line":9,"column":35}},"8":{"start":{"line":10,"column":6},"end":{"line":10,"column":22}},"9":{"start":{"line":11,"column":6},"end":{"line":11,"column":17}},"10":{"start":{"line":14,"column":2},"end":{"line":14,"column":15}},"11":{"start":{"line":15,"column":2},"end":{"line":18,"column":5}},"12":{"start":{"line":16,"column":4},"end":{"line":16,"column":59}},"13":{"start":{"line":17,"column":4},"end":{"line":17,"column":27}},"14":{"start":{"line":19,"column":2},"end":{"line":24,"column":5}},"15":{"start":{"line":20,"column":4},"end":{"line":22,"column":5}},"16":{"start":{"line":21,"column":6},"end":{"line":21,"column":16}},"17":{"start":{"line":23,"column":4},"end":{"line":23,"column":13}},"18":{"start":{"line":25,"column":2},"end":{"line":25,"column":36}},"19":{"start":{"line":25,"column":26},"end":{"line":25,"column":34}},"20":{"start":{"line":26,"column":2},"end":{"line":26,"column":13}},"21":{"start":{"line":29,"column":0},"end":{"line":29,"column":29}}},"branchMap":{"1":{"line":9,"type":"binary-expr","locations":[{"start":{"line":9,"column":19},"end":{"line":9,"column":29}},{"start":{"line":9,"column":33},"end":{"line":9,"column":34}}]},"2":{"line":20,"type":"if","locations":[{"start":{"line":20,"column":4},"end":{"line":20,"column":4}},{"start":{"line":20,"column":4},"end":{"line":20,"column":4}}]}}};
}
__cov_uFernoVyibfwDLJr3wZNbg = __cov_uFernoVyibfwDLJr3wZNbg['/Users/Work/www/Projects/nlp_compromise/test/perf_tests/pos_test/reasons.js'];
__cov_uFernoVyibfwDLJr3wZNbg.s['1']++;const findReasons=function(text){__cov_uFernoVyibfwDLJr3wZNbg.f['1']++;__cov_uFernoVyibfwDLJr3wZNbg.s['2']++;let reasons={};__cov_uFernoVyibfwDLJr3wZNbg.s['3']++;let count=0;__cov_uFernoVyibfwDLJr3wZNbg.s['4']++;for(let i=0;i<text.sentences.length;i++){__cov_uFernoVyibfwDLJr3wZNbg.s['5']++;for(let o=0;o<text.sentences[i].terms.length;o++){__cov_uFernoVyibfwDLJr3wZNbg.s['6']++;let r=text.sentences[i].terms[o].reason;__cov_uFernoVyibfwDLJr3wZNbg.s['7']++;reasons[r]=(__cov_uFernoVyibfwDLJr3wZNbg.b['1'][0]++,reasons[r])||(__cov_uFernoVyibfwDLJr3wZNbg.b['1'][1]++,0);__cov_uFernoVyibfwDLJr3wZNbg.s['8']++;reasons[r]+=1;__cov_uFernoVyibfwDLJr3wZNbg.s['9']++;count+=1;}}__cov_uFernoVyibfwDLJr3wZNbg.s['10']++;let arr=[];__cov_uFernoVyibfwDLJr3wZNbg.s['11']++;Object.keys(reasons).forEach(k=>{__cov_uFernoVyibfwDLJr3wZNbg.s['12']++;let percent=parseInt(reasons[k]/count*100,10);__cov_uFernoVyibfwDLJr3wZNbg.s['13']++;arr.push([k,percent]);});__cov_uFernoVyibfwDLJr3wZNbg.s['14']++;arr=arr.sort((a,b)=>{__cov_uFernoVyibfwDLJr3wZNbg.s['15']++;if(a[1]>b[1]){__cov_uFernoVyibfwDLJr3wZNbg.b['2'][0]++;__cov_uFernoVyibfwDLJr3wZNbg.s['16']++;return-1;}else{__cov_uFernoVyibfwDLJr3wZNbg.b['2'][1]++;}__cov_uFernoVyibfwDLJr3wZNbg.s['17']++;return 1;});__cov_uFernoVyibfwDLJr3wZNbg.s['18']++;arr=arr.filter(a=>{__cov_uFernoVyibfwDLJr3wZNbg.s['19']++;return a[1]>0;});__cov_uFernoVyibfwDLJr3wZNbg.s['20']++;return arr;};__cov_uFernoVyibfwDLJr3wZNbg.s['21']++;module.exports=findReasons;
